<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class IconShopTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dw = Carbon::now()->toDateTimeString();
        
        DB::table('icons')->insert([
            ['icon' => 'gi-sh gi-sh-slim-fit-pants', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-sweatpants', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-bag', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-circle-skirt', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-pegged-pants', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-flat-shoes', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-leather-shoes', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-leather-gloves', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-ballets-flats', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-winter-hat', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-long-sleeveless-dress', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-draped-top', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-hobo-bag', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-cocktail-dress', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-vest', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-pants', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-oxford-wave-blazer', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-shutter-sunglasses', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-drees', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-shopping-bag', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-sweater', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-denim-jacket', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-mannequin', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-harem-pants', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-pilot-sunglasses', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-denim-shirt', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-boxer', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-dress-with-butterfly-sleeves', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-loafer', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-rain-boots', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-slit-skirt', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-boyfriend-low-jean', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-bow-tie', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-leggins', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-chiffon-suffle-blouse', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-sleepers', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-dress', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-padded-vest', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-watches', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-belt', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-bag-1', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-men-hat', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-sneakers', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-sneaker', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-cotton-cardigan', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-trench-coat', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-backpack', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-denim-shorts', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-collarless-cotton-shirt', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-briefcase', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-v-neck-shirt', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-men-socks', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-nylon-jacket', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-tank-top', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-hat', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-jewelry-set', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-hooded-jacket', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-barrel-handbag', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-long-bandeau-dress', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-peplum-top', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-jersey-blazer', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-tie', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-chinos-pants', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-leather-biker-jacket', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-flip-flops', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-leather-chelsea-boots', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-henley-shirt', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-off-the-shoulder-dress', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-scarf-on-hanger', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-chiffon-dress', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-jeans', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-lyocell-shirt-dress', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-lingerine-set', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-high-heels', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-ankle-boots', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-purse', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-messenger-bag', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-one-shoulder-dress', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-wool-boots', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-knit-hat-with-pom-pom', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-cotton-polo-shirt', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-peplum-skirt', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-oxford-wave-suit-pants', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-gladiator-sandal', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-leather-derby-shoe', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-jersey-wrap-dress', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-high-heel', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-cat-eye-glasses', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-peplum-skirt-1', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-bucket-bag', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-wool-gloves', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-t-shirt-with-design', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-formal-shirt', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-chino-shorts', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-platform-sandals', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-long-sleeves-t-shirt', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-tulle-skirt', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-jumpsuit', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-women-socks', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-sh gi-sh-flare-pants', 'created_at' => $dw, 'updated_at' =>  $dw ]
        ]);
    }
}
