<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class IconAcquaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dw = Carbon::now()->toDateTimeString();
        
        DB::table('icons')->insert([
            ['icon' => 'gi-buil gi-buil-badge', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-blueprint', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-blueprint-1', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-blueprint-2', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-browser', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-building', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-building-1', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-building-2', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-building-3', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-building-4', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-catalogue', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-chat', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-chat-1', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-chat-2', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-construction', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-contract', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-duplex', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-house', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-house-1', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-house-2', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-house-3', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-house-4', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-house-5', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-house-6', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-house-7', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-house-8', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-house-9', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-house-10', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-house-11', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-house-12', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-house-13', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-house-14', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-house-15', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-house-16', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-house-key', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-mansion', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-mansion-1', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-money-flow', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-mortgage', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-newspaper', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-newspaper-1', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-newspaper-2', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-panel', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-phone-call', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-presentation', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-presentation-1', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-real-estate', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-real-estate-1', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-real-estate-2', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-real-estate-3', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-seller', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-seller-1', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-seller-2', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-seller-3', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-seller-4', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-seller-5', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-shield', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-swimming-pool', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-unprotected', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-web-page', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-bench', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-billboard', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-bridge', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-building2', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-building-12', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-building-22', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-building-32', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-building-42', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-bus-stop', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-cafe', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-church', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-city', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-city-hall', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-electric-tower', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-factory', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-ferris-wheel', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-fire-hydrant', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-fountain', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-hospital', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-hot-dog', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-house2', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-monument', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-phone-booth', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-pointer', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-police', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-school', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-shop', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-shop-1', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-shop-2', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-signboard', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-skyscrapper', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-skyscrapper-1', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-street-light', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-street-light-1', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-traffic-light', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-traffic-sign', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-bar', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-bathtub', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-bedroom', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-bellboy', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-booking', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-clothes', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-coffee', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-email', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-golf', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-gym', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-hotel', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-hotel-1', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-house3', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-key', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-lift', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-luggage', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-no-smoking', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-relax', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-restaurant', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-room-service', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-room-service-1', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-room-service-2', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-room-service-3', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-safebox', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-smartphone', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-smartphone-1', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-smartphone-2', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-swimming-pool2', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-taxi', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-buil gi-buil-water-tap', 'created_at' => $dw, 'updated_at' =>  $dw ]
        ]);
    }
}
