<?php

use Carbon\Carbon;
use Illuminate\Database\Seeder;

class IconFitnessTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $dw = Carbon::now()->toDateTimeString();
        
        DB::table('icons')->insert([
            ['icon' => 'gi-fit gi-fit-judo-fighter', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-karate', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-karate-1', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-karate-fighter', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-karate-high-kick', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-karate-master', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-aerobica', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-circuito-kids', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-dança', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-fisioterapia', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-pilates', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-yoga', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-people', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-people-1', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-people-2', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-people-3', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-people-4', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-people-5', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-people-6', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-people-7', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-people-8', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-people-9', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-people2', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-people-12', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-people-22', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-people-32', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-people-42', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-two', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-alarm-clock', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-apple', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-athlete', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-beef', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-bicycle', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-blender', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-broccoli', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-calendar', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-check-list', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-chronometer', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-dumbbell', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-dumbbell-1', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-energy-drink', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-fast-food', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-fish', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-forest', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-goal', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-hand-grip', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-jumping-rope', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-kettlebell', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-lotus-position', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-lotus-position-1', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-mat', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-measuring-tape', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-milk', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-milkshake', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-muscle', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-music-player', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-no-drinks', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-pilates2', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-protein', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-pulse', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-rest', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-runner', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-salad', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-slim-down', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-smartphone', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-smartwatch', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-sport-bag', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-sport-shoe', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-stationary-bike', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-studying', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-swimming', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-tea', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-treadmill', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-water', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-watermelon', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-weighing-scale', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-yin-yang', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-yoga-ball', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-doing-pushups', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-flexing-knees-with-arms-up', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-flexing-waist', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-flexing-waist-down', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-flexing-waist-to-feet', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-laying-on-his-back-with-his-knees-on-his-chest', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-on-floor-flexing-backwards', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-on-his-knees', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-on-his-knees-stretching-arms-on-floor', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-on-his-knees-stretching-back', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-on-his-knees-stretching-side-view', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-on-his-knees-with-head-on-floor', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-on-squat-position-turning-waist', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-on-the-floor-flexing-body', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-sitting-on-the-floor-stretching-leg-and-waist', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-squatting', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-standing-on-his-right-leg-stretching-left-leg-and-right-arm', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-standing-on-one-leg', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-standing-on-right-leg-stretching-leg-and-arms', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-stretching-back', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-stretching-both-arms-and-legs', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-stretching-left-leg-and-bending-waist', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-stretching-leg-and-arms', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-stretching-legs-and-flexing-body', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-stretching-legs-and-waist', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-supporting-himself-on-one-arm-and-stretching-right-arm', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-man-up-flexing-to-right', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-bending-waist-to-feet-with-stretching-leg', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-flexing-body', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-flexing-waist-to-feet', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-honding-her-body-with-arms-and-legs', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-laying-down-lifting-head', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-laying-on-the-floor-stretching-right-leg', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-lifting-left-leg', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-on-her-knees-looking-up', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-on-her-knees-stretching-arms', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-on-lotus-position-front-view', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-sitting-on-the-floor-stretching-head', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-sitting-on-the-floor-stretching-left-leg', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-standing-on-her-arms', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-standing-on-one-leg-lifting-left-leg', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-standing-on-right-leg-with-left-leg-up', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-stretching-and-flexing-legs-with-arms-up', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-stretching-arms-and-flexing-legs', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-stretching-back', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-stretching-her-body-on-the-floor', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-stretching-left-leg', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-stretching-on-floor', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-upside-down-stretching-body', 'created_at' => $dw, 'updated_at' =>  $dw ],
            ['icon' => 'gi-fit gi-fit-woman-with-left-leg-up-and-flexed', 'created_at' => $dw, 'updated_at' =>  $dw ],        ]); 
    }
}
